### ISSUE TITLE
Dataset extraction location

### ISSUE THREAD

**Issue by gunshi** [hermannsblum/bdl-benchmark#1]
Hi,
thanks for the benchmark and code, i'm sure it will be super helpful to the community.

I'm having some trouble with tweaking the location where the fishyscapes dataset gets downloaded by default since that's abstracted out by tensorflow_datasets i assume and i can't figure out from the documentation which config file/function argument to change. It gets downloaded to my home directory for now, where i run into space issues.
Could you guide me to the exact location in code where i can specify my custom path?
Thanks!
Gunshi

**Comment by hermannsblum** [comment]
Hi!
As we follow the tf-datasets API, you can just [pass an argument](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/DatasetBuilder) to the dataset when building it: 

```
from bdlb.fishyscapes.fishyscapes_tfds import Fishyscapes
data_builder = Fishyscapes(data_dir=<insert here>)
data = data_builder.as_dataset(split='validation')
```

Another option is to just link `~/tensorflow_datasets` to a location of your choice.
We so far don't have a specified API for this in the BDL-Benchmarks, so you cannot just use the `.load()` API, this is a good point that we will look at for integration.

**Comment by gunshi** [comment]
Thanks!
